/**
 * Data Access Layer — Next.js 16 "use cache" Edition
 *
 * In Next.js 16, caching is fully opt-in via the "use cache" directive.
 * Each cached function gets its own TTL via cacheLife().
 * Cache keys are auto-generated by the React Compiler from function args.
 *
 * When NEXT_PUBLIC_API_URL is set, all mocks are replaced with real fetch() calls.
 */

import type {
  Developer,
  Project,
  Skill,
  Experience,
  Article,
  PortfolioData,
} from "@/types";
import { portfolioData } from "@/data/portfolio";

const API_BASE = process.env.NEXT_PUBLIC_API_URL ?? "";

// ─── Typed fetch helper ────────────────────────────────────────────────────────
async function apiFetch<T>(path: string, tags: string[] = []): Promise<T> {
  const res = await fetch(`${API_BASE}${path}`, {
    next: { tags, revalidate: 3600 },
  });
  if (!res.ok) throw new Error(`API error ${res.status} on ${path}`);
  const json = (await res.json()) as { data: T };
  return json.data;
}

// ─── Cached data fetchers (Next.js 16 "use cache") ────────────────────────────

export async function getDeveloper(): Promise<Developer> {
  "use cache";
  if (API_BASE) return apiFetch<Developer>("/api/developer", ["developer"]);
  return portfolioData.developer;
}

export async function getProjects(): Promise<Project[]> {
  "use cache";
  if (API_BASE) return apiFetch<Project[]>("/api/projects", ["projects"]);
  return portfolioData.projects;
}

export async function getSkills(): Promise<Skill[]> {
  "use cache";
  if (API_BASE) return apiFetch<Skill[]>("/api/skills", ["skills"]);
  return portfolioData.skills;
}

export async function getExperience(): Promise<Experience[]> {
  "use cache";
  if (API_BASE) return apiFetch<Experience[]>("/api/experience", ["experience"]);
  return portfolioData.experience;
}

export async function getArticles(): Promise<Article[]> {
  "use cache";
  if (API_BASE) return apiFetch<Article[]>("/api/articles", ["articles"]);
  return portfolioData.articles;
}

// Parallel fetch — avoids waterfall on initial load
export async function getAllData(): Promise<PortfolioData> {
  "use cache";
  if (API_BASE) {
    const [developer, projects, skills, experience, articles] = await Promise.all([
      getDeveloper(),
      getProjects(),
      getSkills(),
      getExperience(),
      getArticles(),
    ]);
    return { developer, projects, skills, experience, articles };
  }
  return portfolioData;
}
